### PR TITLE
PMM-7106 Migrate to Go modules

### PR DESCRIPTION
**Pull request by AlekSi**

### CODE REVIEW

**Comment by BupycHuk** [comment]
It would be good to have FB to see if tests still works there

**Review by BupycHuk — CHANGES_REQUESTED** [review]
Let's add FB to check if it still works.

**Comment by AlekSi** [comment]
Yeah, except that FBs currently do not work :)

**Comment by palash25** [comment]
fixed in 36c3265c690f46e98ce3deb78587525197b0d08d

**Pull request closed without merging**
