### PR TITLE
PMM-6401 fixes tests after replacing prometheus with victoriametrics

### PR DESCRIPTION
**Pull request by f41gh7**
replaces https://github.com/Percona-Lab/pmm-api-tests/pull/133 

submodules PR https://github.com/Percona-Lab/pmm-submodules/pull/1183

### CODE REVIEW

**Comment by BupycHuk** [comment]
What's the difference?

**Comment by f41gh7** [comment]
source branch, previous PR was from fork, so i cannot add it to pmm-submodules

**Comment by BupycHuk** [comment]
looks like we still have prometheus.log in logs output https://pmm.cd.percona.com/job/pmm2-api-tests/4683/console

**Comment by f41gh7** [comment]
Thats strange, i wasn't able to find it at server docker image:
```bash
docker run --rm  --entrypoint=/bin/sh perconalab/pmm-server-fb:PR-1183-7f96019 -c 'find / -name "prometheus.log"'
```

**Comment by BupycHuk** [comment]
it means that something generates a file after the start
try to run docker image, wait a little bit and then call `docker exec`

**Comment by f41gh7** [comment]
> it means that something generates a file after the start
> try to run docker image, wait a little bit and then call `docker exec`

yep, found bug.

**Review by BupycHuk — APPROVED** [review]

**Pull request merged**
