### PR TITLE
PMM-6909 Rule template API tests

### PR DESCRIPTION
**Pull request by artemgavrilov**
[PMM-6909](https://jira.percona.com/browse/PMM-6909)
[PMM-7095](https://jira.percona.com/browse/PMM-7095)

- [ ] https://github.com/percona/pmm-managed/pull/541

FB: https://github.com/Percona-Lab/pmm-submodules/pull/1271

### CODE REVIEW

**Comment by artemgavrilov** [comment]
Ahhhh... CI stuck for some reason 😤

**Comment by artemgavrilov** [comment]
Trying to figure out what is the problem.

**Review by palash25 — APPROVED** [review]

**Review by AlekSi — CHANGES_REQUESTED** [review]
Jenkins is still broken, I run tests manually, they fail. pmm-managed PR is merged to unblock future work; please create a new PR if the problem is on pmm-managed side.

Please also check the latest commits

**Comment by artemgavrilov** [comment]
> Jenkins is still broken, I run tests manually, they fail. pmm-managed PR is merged to unblock future work; please create a new PR if the problem is on pmm-managed side.
> 
> Please also check the latest commits

On my local setup tests are passed. I used `managed` devcontainer build form `release/2.13` branch as tests target.
How did you run tests?

**Review by AlekSi — APPROVED** [review]

**Pull request merged**
