### PR TITLE
PMM-6969 Rules API tests

### PR DESCRIPTION
**Pull request by artemgavrilov**
[PMM-6969](https://jira.percona.com/browse/PMM-6969)

- [ ] https://github.com/percona/pmm-managed/pull/554

FB: https://github.com/Percona-Lab/pmm-submodules/pull/1295

### CODE REVIEW

**Comment by AlekSi** [comment]
Merge conflicts

**Comment by artemgavrilov** [comment]
> Merge conflicts

Resolved

**Review by palash25 — APPROVED** [review]

**Review by BupycHuk — CHANGES_REQUESTED** [review]
Can we cleanup created objects after tests?

**Comment by artemgavrilov** [comment]
> Can we cleanup created objects after tests?

Yes, we can!

**Review by palash25 — APPROVED** [review]

**Review by AlekSi — APPROVED** [review]

**Pull request merged**
